### ISSUE TITLE
doesn't show any errors in inferior-lisp buffer?

### ISSUE THREAD

**Issue by joefromct** [hylang/hy-mode#28]
I'm not seeing any errors in the inferior-lisp buffer... it appears as if nothing happens when an error should occur.

I have also tried setting --spy and --show-tracebacks as documented [here](http://hy.readthedocs.org/en/latest/language/cli.html#cmdoption--show-tracebacks).

**Example**: 
    => (\* 10  0 )
    (10L \* 0L)
    0L

However division of zero echos nothing:

```
=> (/ 10 0 ) 
(10L / 0L)
=> 
```

This is making it more difficult to adapt to the syntax... any tips?

**Comment by gilch** [comment]
On Spacemacs on Windows, I can also see the stderr, but I do leave the `--spy` mode on, if that matters. @joefromct, is this still broken?

**Comment by ekaschalk** [comment]
I'm going to close this issue as I don't exerpience this either. If it occurs again somehow we can reopen.
