### ISSUE TITLE
Make indentation rules match the Hy style guide.

### ISSUE THREAD

**Issue by gilch** [hylang/hy-mode#39]
[The Hy Style Guide](https://github.com/hylang/hy/blob/master/docs/style-guide.rst) states that

> Indentation shall be 2 spaces (no hard tabs), except when matching the indentation of the previous line.

The MELPA version of Hy-mode only gives me one space when I hit return or when I reformat a form. I shouldn't have to fight the editor to maintain the standard style.

``` Hy
;; current behavior
(do
 (print "Hello, World!"))
;; expected behavior
(do
  (print "Hello, World!"))
```

**Comment by philiparvidsson** [comment]
Another problem along the same lines:

Hy-mode is intelligent enough to only indent one level (i.e. 2 spaces) after `(if ...`, but threats `(if-not x ...` as a function call and aligns the second row to the first:

```
;; current behavior
(if (x)
  (y))
(if-not (x)
        (y))

;; expected behavior
(if (x)
  (y))
(if-not (x)
  (y))
```

**Comment by ekaschalk** [comment]
Do you have any thoughts on which forms should be indented special?

Right now, any form matching: `\\(?:\\S +/\\)?\\(def\\|with-\\|with_\\|fn\\|lambda\\)` will have the 'if-like' indentation.

Eg.

```
(lambda x
  y)
(with-my-own-context x
  y)
```

So adding `if-not` and such variations are simple, what else though? 

For example, I think `as->` is a good candidate for special indentation, possibly also `ap-pipe`.
