### ISSUE TITLE
Consider tagging a release

### ISSUE THREAD

**Issue by ccharles** [hylang/hy-mode#41]
It's great that `hy-mode` is available in MELPA. However, since there are no tagged releases it is not available via MELPA stable. 

Please consider tagging a release, e.g. `0.1`, so that MELPA stable users can easily install `hy-mode`.

**Comment by Kodiologist** [comment]
I don't think anybody is maintaining hy-mode right now. Any volunteers?

**Comment by gilch** [comment]
@hylang/core, do we have a maintainer currently? Is anybody left good with emacs lisp?

I might take up the mantle myself if no-one better qualified volunteers, since I primarily use Spacemacs, but I'm still not that confident with elisp, so don't expect much for a while.

**Comment by Kodiologist** [comment]
I've done some stuff in Emacs Lisp, like [Daylight](https://github.com/Kodiologist/Daylight), but I can't commit to this; I'd rather spend free programming time on Hy itself.

**Comment by microamp** [comment]
While I haven't written in (and contributed to) Hy for a very long time, I can give it a shot.

**Comment by ekaschalk** [comment]
I'm open to maintaining hy-mode. I use hy professionally for data-sciency work. I'm relatively knowledgeable in elisp (I maintain an emacs blog: http://www.modernemacs.com/). I have a tentative fix to the dictionary with strings indentation issue.

**Comment by microamp** [comment]
@ekaschalk Awesome, I love your blog. It's great to hear someone using Hy professionally. Anyway, you get my vote. 👍

**Comment by gilch** [comment]
@ekaschalk seems to have some approval. @hylang/core, what would be the process of making him the maintainer? Or should we wait a while for more volunteers?

**Comment by Kodiologist** [comment]
I think it should be first-come, first-serve. People don't exactly line up around the block for this sort of thing, anyway.

**Comment by gilch** [comment]
Three weeks with no further comment. @ekaschalk, I guess your it.

I don't know how to set up permissions in this repo for a new hy-mode maintainer. Does he have to be a Hy Society member first? Also, I'm just a member, not an owner, so maybe I can't do it.

@paultag?

**Comment by Kodiologist** [comment]
I went to the settings tab of the repository and added him as a collaborator.

**Comment by ekaschalk** [comment]
Thanks for the add, I'll start updating soon.

**Comment by ekaschalk** [comment]
I've refactored Hy-mode, see VERSION, and have tagged release 1.0. I have a large hy codebase to test my changes against but may have missed things, please let me know if any updates break anything.

**Comment by ccharles** [comment]
I can confirm that, as of the most recent build, [`hy-mode` now shows up in MELPA stable][1]. Thanks for taking the lead on maintenance, @ekaschalk!

[1]: https://stable.melpa.org/#/hy-mode
