### ISSUE TITLE
Inferior lisp history getting corrupted

### ISSUE THREAD

**Issue by gilch** [hylang/hy-mode#43]
When running a hy-mode inferior-lisp in Spacemacs, I can use the up arrow to recall earlier repl entries. And the down arrow reverses this. But if you go down one item too far, then the entry becomes a duplicate of the prompt `=>`, and the history is lost. Also, it can't be deleted because it's readonly. You can send it to the repl (which results in an error) to avoid restarting the repl.

I'm not sure if this is a problem with hy-mode, hy's repl, or the spacemacs layer somehow.

**Comment by gilch** [comment]
This is happening again after spacemacs ran a MELPA update.

**Comment by ekaschalk** [comment]
This is happening with hy master? I just updated Spacemacs/updated packages and do not have the issue.

**Comment by gilch** [comment]
I did an update and tried testing that again. Now `SPC m s i` from a hy-mode buffer starts Common Lisp instead of Hy.

**Comment by gilch** [comment]
I added `(require 'spacemacs-hy)` to `.spacemacs` and now I can start the hy repl with `SPC m '`. It doesn't seem to have the issue with history corruption.

**Comment by ekaschalk** [comment]
I just discontinued the old way of starting an inferior hy. It is now executed via `run-hy`.

If you're using Hy master branch, you now have to use `spacemacs-hy`. The reason for this is I'm preparing to push a new release with 40+ commits and PR Spacemacs.

I was going to create a separate issue soon - feedback and bug reports are very welcome and needed as I prepare to push finalized autocompletion/eldoc to melpa stable.
