### ISSUE TITLE
tab completion not working in inferior lisp

### ISSUE THREAD

**Issue by gilch** [hylang/hy-mode#47]
At least not in my current Spacemacs setup (develop branch with Python layer). Hy's command line repl does have tab completions though.

**Comment by ekaschalk** [comment]
Autocompletion now auto starts up on file load/activating a python environment. I've updated it to work under the new internal processes, should be solid enough to use now.

It now autocompletes in shell as well. Still doesn't complete all symbols - but this is an issue to solve in hy not hy-mode.
