### ISSUE TITLE
Indentation requests and bugs.

### ISSUE THREAD

**Issue by ekaschalk** [hylang/hy-mode#48]
@gilch @Kodiologist 

I've rewritten hy-mode indentation taking from Clojure. We now have:

1. 2-spaces hy style guide now followed.
2. Both dicts and lists with strings at start should be indented correctly in all cases.

Let me know if any bugs have popped up, it's passing on all my files.

Also let me know if any remaining requests for indentation, in particular adjusting the specform to indent things like `as->`, `ap-pipe/if/...` and so on.

**Comment by gilch** [comment]
The `,` special form for tuples should align args like a function call.

Current.
```
(, 1
 2
 3)
```
Expected
```
(, 1
   2
   3)
```

**Comment by ekaschalk** [comment]
Fixed the tuple alignment. I've been refactoring the indentation, almost all clean now.

**Comment by gilch** [comment]
Smartparens doesn't duplicate it anymore, but, the ``` ` ``` is getting paired and indented like a bracket. For example,
```Hy
(if b
  `x
    `y)
```
Expected
```Hy
(if b
  `x
  `y)
```

**Comment by ekaschalk** [comment]
Fixed with d5cf1890c938a17dcef37b0d70230ab7e2dcfe03

I've finished rewriting the indentation, should be solid now.

**Comment by ekaschalk** [comment]
Found an issue occuring *only* when starting a form with exactly `.-`:

```
(.-a d
    e)
```

Expected:
```
(.-a d
     e)
```

**Comment by gilch** [comment]
Hy's `if` is variadic, (like in Arc Lisp). When taking more than three arguments, it needs to be indented like Clojure's `cond`, instead of Clojure's `if`.

Current
```Hy
(if 1 2
  3 4
  5 6
  7 8
  9)
```
Expected
```Hy
(if 1 2
    3 4
    5 6
    7 8
    9)
```
This used to work both ways, like a call if 1 2 were on the same line, and like a defn if 1 was by itself, e.g.
```Hy
(if 1 2
    3)
(if 1
  2
  3)
```

In other Lisps, it's normal to indent `if` just like a function call. Emacs is unusual because it dedents the _else_ clasue. And Clojure is unusual because it dedents both _then_ and _else_ clauses.

I personally think it would be fine if `if` were indented just like a regular call all the time. It doesn't have an implicit-do body. But in either case, the `cond`-like form should not get the dedent.

**Comment by gilch** [comment]
The `,` is just a symbol, but even in `[]` and `{}`, it gets indented like a tuple special form--
```
[, 1
   2 3]
{, 1
   2 3}
```
Expected
```
[, 1
 2 3]
{, 1
 2 3}
```

**Comment by ekaschalk** [comment]
Tuple indentation fixed with 57078d7a3adbff17dd7ed9fcfe2326d2fe02d1ee
If treated as function with eb808be9b00de514a470ad96c5694cef633204e8
Tag macro indentation with c26bc900be071dbe2488c12c787d953c21232ed8

There was no bug with `.-` symbols.

If you have preference for the final case I know how to implement that.

**Comment by ekaschalk** [comment]
I believe indentation to be settled now. Going to close this.

**Comment by gilch** [comment]
Sets seem to throw off indentation
```Hy
(foo #{}
      1
      2)
```
expected
```Hy
(foo #{}
     1
     2)
```

**Comment by ekaschalk** [comment]
Fixed. Before tag macros would indent 1 past the hash, they now indent at the hash as seen in the set literals.

**Comment by ekaschalk** [comment]
Forms opening with another form throw normal indentation off.

    ((if pred f g) a
     b)

Expected to follow standard indentation rules, instead always indents at the opening. Believe it is because it indents parenthesis like a bracket-like.
