### ISSUE TITLE
back- slurp and barf don't recognize unquote-splice

### ISSUE THREAD

**Issue by gilch** [hylang/hy-mode#52]
In Emacs lisp, slurp and barf consider the `,@` prefix to be part of the bracket.
```Elisp
(foo 1 2 ,@(3 4) 5)
(foo 1 ,@(2 3 4) 5)  ; slurp back
(foo 1 2 ,@(3 4) 5)  ; barf back
```
In hy-mode, the equivalent `~@` is considered a symbol
```Hy
(foo 1 2 ~@(3 4) 5)
(foo 1 2 (~@ 3 4) 5)  ; slurp back
(foo 1 2 ~@ (3 4) 5)  ; barf back
```

And `,` is still considered prefix, but it should be a symbol in Hy.

**Comment by ekaschalk** [comment]
Fixed with some minor syntax table updates.
