### ISSUE TITLE
Support new bracket string syntax

### ISSUE THREAD

**Issue by gilch** [hylang/hy-mode#54]
See hylang/hy#1379.

This needs to be recognized as a string and not auto-indented.

It would also be nice (if possible) if hy-mode supported custom highlighting in these strings for certain bracket names. For example, the contents of a string starting with `#[reST[` would be highlighted as [reStructuredText](http://docutils.sourceforge.net/rst.html), or with `#[Python[` would be highlighted as Python.

**Comment by ekaschalk** [comment]
> It would also be nice (if possible) if hy-mode supported custom highlighting in these strings for certain bracket names.

It might be possible with: https://github.com/purcell/mmm-mode.

As of emacs 25.2 it should be possible to even use rest/python indentation within the string literal. That feature was added for better source block editing in `org-babel` so I'm not sure how straightforward (or even desirable) that would be in this case.

**Comment by ekaschalk** [comment]
I have implemented the new bracket string literals, they indent/highlight/etc.. appropriately.

However, smartparens (and all functions running on `forward-list` syntax traversal) does not work on that section.

That is, `#[[hi]]` will have both the first and second `]` jump to the first `[` while the second `[` jumps to nothing.

`lua-mode` has almost the same issue, despite being done differently.

It has to do with setting a `string-fence` syntax property on a `parenthesis` syntax character.

I'm not sure how long/if this can be resolved, context-sensitive highlighting is difficult to work with.

**Comment by ekaschalk** [comment]
Bracket string literals now supported with 0f195e75ea4bd939c238f72f84cb5c3a40da7083

The smartparens issue is present but minor. Also slurping a bracket literal requires two slurps, one for the `#[` and the other slurps the rest.

Right now it doesn't require the `#[DELIM-1[hi there]DELIM-2]` have `DELIM-1 == DELIM-2`. This is easy enough to change if desired.

**Comment by ekaschalk** [comment]
Closing this unless, will investigate python highlighting at a later point, not a priority.
