### ISSUE TITLE
| behaves strangely

### ISSUE THREAD

**Issue by gilch** [hylang/hy-mode#55]
I'm not sure if this is hy-mode or something else in spacemacs. I know `|` is used to quote symbol names in Common Lisp, so you don't have to use `\` escapes in them. But in Hy, it's an operator (currently anyway, see hylang/hy#1117), and needs to act like a symbol in its own right.

**Comment by ekaschalk** [comment]
Fixed with: 685c53764a45eaa9f64a001ee81475359b6eba90
