### ISSUE TITLE
Repl not working: (void-function xterm-color-filter)

### ISSUE THREAD

**Issue by kbauer** [hylang/hy-mode#60]
Any interacton with the inferior-lisp repl results in

```
Debugger entered--Lisp error: (void-function xterm-color-filter)
  xterm-color-filter("\n=> ")
  comint-output-filter(#<process Hy> "\n=> ")
```

Observed in 
- Emacs 25.2.1 (Cygwin, 64bit on Windows 10)
- Emacs 25.1.1 (Windows 10 native, x86_64-w64-mingw32)

**Comment by ekaschalk** [comment]
Didn't realize `xterm-color` was not an emacs core package, fixed. If you want colored error messages then install `xterm-color` from melpa.
