### ISSUE TITLE
hy-mode no longer activates automatically for .hy-files

### ISSUE THREAD

**Issue by philiparvidsson** [hylang/hy-mode#62]
previously, you could open a .hy-file with hy-mode installed and emacs would automatically enable hy-mode. this is no longer the case, and hy-mode needs to be activated manually (or configured in init.el to be enabled automatically for hy-files)

**Comment by ekaschalk** [comment]
`.hy-file` is a file extension for Hy? Sure I can go add it.

**Comment by philiparvidsson** [comment]
You misinterpreted. I mean files with a .hy filename ending. They don't activate hy-mode automatically anymore. I.e. opening a file named "foo.hy" does not automatically activate hy-mode.

**Comment by ekaschalk** [comment]
What is your version of Hy and hy-mode? I haven't heard that happening.

**Comment by philiparvidsson** [comment]
`hy-mode-20171030.1023` and `hy 0.13.0`

**Comment by ekaschalk** [comment]
Do you see hy in both of the emacs variables

 `auto-mode-alist`
`interpreter-mode-alist`

**Comment by philiparvidsson** [comment]
hy is in neither.

**Comment by philiparvidsson** [comment]
it seems I need to (require 'hy-mode) for it to work. not sure if that was the case before? maybe it was.

**Comment by ekaschalk** [comment]
The

```
(add-to-list 'auto-mode-alist '("\\.hy\\'" . hy-mode))
(add-to-list 'interpreter-mode-alist '("hy" . hy-mode))
```

was unchanged from the original hy-mode, I don't think its behavior would've changed. I'm not sure if the require call is proper to have mandatory or not.

**Comment by philiparvidsson** [comment]
I don't know enough about the Emacs ecosystem to say for sure whether `(require 'hy-mode)` should be needed or not and I probably remember incorrectly. If possible to do it without `require`ing the module, it would be nice to do so (unless it breaks some kind of convention).
