### ISSUE TITLE
FR: syntax highlighting that recognized discard prefix #_ as comment?

### ISSUE THREAD

**Issue by bandresen** [hylang/hy-mode#66]
Feature Request:

The clojure-mode does it.
I checked clojure-mode.el a bit but font-locking makes no sense to me.

Would be nice to have. :-)

**Comment by ekaschalk** [comment]
How does Clojure do it? Is only the immediate form highlighted as a comment? And does this highlighting span multiple lines?

**Comment by bandresen** [comment]
Yeah, see here:

![before](https://i.imgur.com/HrnkIZt.png)
![after](https://i.imgur.com/7aXO44E.png)

**Comment by ekaschalk** [comment]
Ok, sure I can add this. The multiple lines part makes it a bit more involved than the other font-locks.

**Comment by ekaschalk** [comment]
Are indentation rules preserved inside the commented form? Or does it behave like a string, ie. inserting a newline within the captured from will indent at the margin?

I have the former working already. The latter needs requires another approach than font-locks.

**Comment by ekaschalk** [comment]
03322cf34d94ba99aa86f8b3fa213c81a5c185b7 #_ now supported, I checked Clojure and indeed its the former, and I see why.

**Comment by bandresen** [comment]
Doesn't work for me:
```
(defn foo-bar [baz]
  (setv foo (-> (.get baz QUUX)
                (. value)
                first))
  (or foo 0))
```
Only `(. value)` receives the comment font-lock. Other `defns` don't receive any font-lock at all.

**Comment by ekaschalk** [comment]
Any form with other syntax highlighting broke it for the form, moving this keyword to the top fixes this.

However, the constant `0` is also highlighted and still overwrites the comment tag.

So almost solid, have to understand why constants are special.

**Comment by bandresen** [comment]
I can confirm that this works! Thanks @ekaschalk!
