### ISSUE TITLE
defmain is not indented properly

### ISSUE THREAD

**Issue by bandresen** [hylang/hy-mode#69]
Right now the indentation looks like this:
```
(defmain [&rest args]
         (do-something-with args))
```
versus correct indentation is
```
(defmain [&rest args]
  (do-something-with args))
```

[Source for correct indentation](http://docs.hylang.org/en/stable/language/api.html#defmain)

**Comment by ekaschalk** [comment]
Woops I introduced a regression for `def` based functions that I didn't notice because I overwrite locally with some additional config.
