### ISSUE TITLE
Allow Jupyter with Hy Lang Kernel as shell

### ISSUE THREAD

**Issue by davidpham87** [hylang/hy-mode#72]
Hello,

Thanks a lot for this emacs mode, and for the Hy in general. I use Hy Lang for doing data analysis, and it is really useful to have an interpreter running while coding. 

As much I as like the default interpreter, can we maybe extend the mode to use jupyter console with a hy kernel? Moreover, would it be possible to integrate it with [Emacs IPython Notebook](https://github.com/millejoh/emacs-ipython-notebook)?

I would be happy to help, but my knowledge of eLisp are a bit limited. I tried to change the hy interpreter in the mode with different arguments, but I did not have a lot of success.

Thanks a lot for your help!

**Comment by ekaschalk** [comment]
I'm not aware of any integration with EIN. But `org-babel` has https://github.com/brantou/ob-hy, I haven't tried it however.

If you're not aware, `org-babel` is an extension of `org-mode` that handles executing code and displaying output in a similar manner to EIN. Maybe try that?

**Comment by ekaschalk** [comment]
`ob-hy` works as I've just tested for babel. I don't intend to add it into `hy-mode`.

Spacemacs's new hy layer has `ob-hy` downloaded and configured by default. EIN integration is out of scope for `hy-mode` so I'm closing this issue.
