### ISSUE TITLE
completion failing, no logs

### ISSUE THREAD

**Issue by brettgilio** [hylang/hy-mode#81]
I have packaged hy and hy-mode for emacs for https://www.gnu.org/software/guix/

I can get everything to work just fine with hy-mode. The shell runs, but the only thing that doesnt work is completion.

Here is my configuration for it. Do you know what is happening?

https://github.com/brettgilio/guix-system/commit/3d665f71f80790cb3bb6db031c3cbf3512a472ce

**Comment by ekaschalk** [comment]
Hi please provide the version of Hy you are using.

Hy has a habit of breaking my introspection code with updates so it is likely that rather than something with your configuration.

**Comment by brettgilio** [comment]
brettg@guixsd ~ [env]$ hy
hy 0.16.0 using CPython(default) 3.7.0 on Linux
=>

**Comment by ekaschalk** [comment]
Quite a few things are broken apparently.. I don't really find that acceptable. I'm going to work on this again.

**Comment by brettgilio** [comment]
Anything I  can help you with?

**Comment by ekaschalk** [comment]
I'm fixing up jedhy and want to integrate that finally. Figuring out good ways to install Python packages from within Emacs would be the most useful step.

**Comment by ekaschalk** [comment]
I redid most of hy-mode and have autocompletion, eldoc, etc. working now with jedhy.

The completion can be a bit slow so I need to optimize jedhy some and finish up the test suite, then hy-mode should be much improved and ready.

**Comment by ekaschalk** [comment]
Please check out the readme. Autocompletion, doc lookup, etc should now be pretty solid.

Closing but feel free to reopen to provide feedback/issues/etc.
