### ISSUE TITLE
Company mode offers Hy completions in inappropriate buffers after activating hy-mode

### ISSUE THREAD

**Issue by r-zip** [hylang/hy-mode#82]
After activating `hy-mode`, company provides only Hy-related completions. I have observed this problem in both Python and elisp buffers.

I'm using Hy version 0.16.0.'

**Edit**: This problem goes away once I kill the \*Hy Internal\* buffer.

**Comment by ekaschalk** [comment]
Pushed a fix. Do you run spacemacs or is `company-backends` not a local var for you?
