### ISSUE TITLE
describe-mode broken in 1.0.3 via melpa-stable

### ISSUE THREAD

**Issue by waffletower** [hylang/hy-mode#84]
After upgrading via to 1.0.3  I was unable to see hy-mode keybindings (as well as bindings for other modes) via `describe-mode`.  There are other symptoms as well, as my configured hooks (such as paredit) for `hy-mode` and `inferior-hy-mode` are ignored.  I even stripped my other config and still saw the issues.  Would be nice to have a working hy-mode on melpa-stable.  When I used master (`e2d5fecdaec602788aa7123ed13651c888b8d94b`) I don't see any of  these issues.

**Comment by ekaschalk** [comment]
Sure I've just tagged a new release, been 100 commits since the last one. Held off while waiting to see if people raised any issues but no one has so either: it's all working or no one cares enough to report any.

In either case any stable users should be able to use this mode now.
